nome = str(input('Digite seu nome completo: ')).strip()
espacos = nome.replace(' ', '')
prim = nome.split()
print(f'Seu nome em maiúsculas é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
print(f'Seu nome ao todo tem {len(espacos)} letras.')
print(f'Seu primeiro nome tem {len(prim[0])} letras.')
print(f'Seu último nome é {prim[-1]}.')
print(f'Seu último nome tem {len(prim[-1])} letras.')
